[project]
name = "deltatask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.3.0",
    "python-frontmatter>=1.1.0",
    "sqlalchemy>=2.0.0",
]
